services:
  db:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      #- ./postgres_data/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
      - ./init/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - default
  af:
    container_name: airflow_container
    image: apache/airflow:latest
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow_password@db:5432/airflow_db

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins 
    depends_on:
      - db
    networks:
      - default
    command: >
      bash -c "airflow db migrate && airflow standalone"
  
  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    platform: linux/amd64
    volumes:
      - ./dbt/my_project:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app
    enviroment:
      DBT_PROFILES_DIR: "/root/.dbt"
    depends_on:
      - db
    networks:
      - default
    command: debug



networks:
  default:
    driver: bridge   

# airflow user_name = "admin", password = QcACEcMTUsRTkSww
# docker exec -it airflow_container bash -lc 'cat ${AIRFLOW_HOME:-/opt/airflow}/simple_auth_manager_passwords.json.generated'
# docker exec -it airflow_container cat /opt/airflow/simple_auth_manager_passwords.json.generated

